### ISSUE TITLE
Add appendix with list of hackathon guides.

### ISSUE THREAD

**Issue by mheadd** [mheadd/opendata.guide#2]
Collect them all in a new appendix to main document. List is [here](https://github.com/mheadd/opendata.guide#related).

**Comment by JoshData** [comment]
https://usodi.org/2014/11/10/hackathons/

**Comment by mheadd** [comment]
Hmm, there is actually much I disagree with in that post. 

<pre>
Any hackathon built on the assumption that it will conclude with the creation of success 
stories is a hackathon that will fail.
</pre>

All of the things we now know about running hackathons well is the result of holding many, many events and learning what works and what doesn't over time.  I've participated in enough hackathons - and worked at enough government agencies - to know that there isn't always a good replacement for experience.

**Comment by JoshData** [comment]
I guess the take-away I got from it was not to hold a hackathon for the wrong reason, for before having an understanding of reasonable expectations. But I see what you mean.
